name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - published

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: Get version
        id: get_version
        run: echo ::set-output name=version::v-$(cat VERSION.txt)$GITHUB_RUN_NUMBER
      
      - name: Show Version
        run: echo ${{ steps.get_version.outputs.version }}             

      - name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: mimiro/datahub:${{ steps.get_version.outputs.version }}

      - name: Trivy vulnerability scan
        uses : aquasecurity/trivy-action@master
        with :
          image-ref: 'mimiro/datahub:${{ steps.get_version.outputs.version }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'         

      - name: Push Unstable Image to DockerHub
        id: dockerhub_push_unstable
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mimiro/datahub:${{ steps.get_version.outputs.version }}-unstable    
    
      - name: Push Stable Image to DockerHub upon publishing github release
        id: dockerhub_push_stable
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mimiro/datahub:${{ steps.get_version.outputs.version }} , mimiro/datahub:latest                
